export const GETSTARTED_STEP1 = 'GETSTARTED_STEP1';
export const UPDATE_BUSS_INFO = 'UPDATE_BUSS_INFO';
export const GETSTARTED_STEP2 = 'GETSTARTED_STEP2';
export const SET_AUTOCOMPLETE = 'SET_AUTOCOMPLETE';
export const SET_LOCATION = 'SET_LOCATION';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
