export const CLOSE_DIALOG = 'CLOSE_DIALOG';
export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const OPEN_DRAWER = 'OPEN_DRAWER';
export const OPEN_LOGIN_DIALOG = 'OPEN_LOGIN_DIALOG';
export const STORE_RESTRICTED_PAGE = 'STORE_RESTRICTED_PAGE,';
